### PR TITLE
I replaced the outdated encryption with OpenSSL

### PR DESCRIPTION
**Pull request by robertfels**

### CODE REVIEW

**Comment by robertfels** [comment]
https://github.com/jordansamuel/PASTE/issues/106

**Comment by robertfels** [comment]
https://github.com/jordansamuel/PASTE/issues/95
And i added a prevention for SQL injection

**Comment by SandeepSathwik** [comment]
It helped thank you, saved a lot of time

**Comment by jordansamuel** [comment]
thank you for contributing

**Comment by rautamiekka** [comment]
Uh, you're using a hardcoded salt.

**Comment by jordansamuel** [comment]
good catch, fixed.

**Pull request merged**
