### PR TITLE
Changed email password field to field type password

### PR DESCRIPTION
**Pull request by luketainton**
I have changed the SMTP password field as below:
- The field now uses a field type of 'password'. This means that it now obscures text entered into the field.
- I changed the placeholder.
- The value option no longer echos the password. If the password is set, it echos '123456' instead.

### CODE REVIEW

**Comment by luketainton** [comment]
Fixes #92

**Comment by luketainton** [comment]
@jordansamuel

**Comment by jordansamuel** [comment]
I would say this is quite unnecessary as the user has no fallback to see if they have entered the incorrect password, currently there is no SMTP connection check.
Of course, you shouldn't be giving your admin account to people you can't trust 😬
For eavesdropping perhaps a button to show password would be better, and hidden by default.

**Comment by luketainton** [comment]
I'll take a look and see what I can do about having a reveal button.

**Comment by luketainton** [comment]
@jordansamuel The password field hides the password by default, but I've now added a button that toggles a change between it being a password field and a text field. It now reveals/hides the password when pressed.

**Pull request merged**
